core/urls.py
from django.contrib import admin
from django.urls import path ,include
from .views import Index,Contact,detailPage,SignUpView,LogInView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
app_name='core'
urlpatterns = [
path('',Index,name='index'),
path('signup/',SignUpView,name='signup'),
path('login/',LogInView,name='login'),
path('logout/',auth_views.LogoutView.as_view(template_name='core/logout.html'),name='logout'),
path('contact/',Contact,name='contact'),

]
# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

dashbord/urls.py
from django.contrib import admin
from django.urls import path ,include
from .views import Index
from django.conf.urls.static import static
app_name='dashbord'
urlpatterns = [
path('dashbord/',Index,name='index')

]

item/urls.py
from django.contrib import admin
from django.urls import path ,include
from .models import Item
from core.views import detailPage
from .views import AddItemView
app_name='item'
urlpatterns = [
  path('items/<int:pk>/',detailPage,name="detail"),
  path('create-item',AddItemView,name='add-item')

]

marketplace/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('item.urls')),
    path('',include('dashbord.urls'))
]

dashbord/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=200)
    class Meta:
        ordering=('name',)
        verbose_name_plural='categories'
    def __str__(self):
        return self.name    
    
class Item(models.Model):
    #if we delete a category all its items will be deleted
    Category=models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    descreption=models.TextField(blank=True,null=True)
    price=models.FloatField()
    image=models.ImageField(upload_to='items_images',blank=True,null=True)
    is_sold=models.BooleanField(default=False)
    created_by=models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=('name',)
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    pass
  
  
class SignUpForm(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
      model=User
      fields=('username','email','password1','password2')
    def save(self,commit=True):
      user=super(SignUpForm, self).save(commit=False)
      user.email=self.cleaned_data['email']
      if commit:
        user.save()
        
      return user       
      
    

item/forms.py
from django import forms
from .models import Item
class CreateItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=('Category','name','descreption','price','image',)

core/views.py
from django.shortcuts import render, redirect,get_object_or_404
from item.models import Item , Category
from django.contrib.auth import login
from .forms import SignUpForm,LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth.decorators import login_required
# Create your views here.
def Index(request):
    items=Item.objects.filter(is_sold=False)[:8]
    categories=Category.objects.all()
    context={
        'items':items,
        'categories':categories
    }
    return render(request,'core/index.html',context)

def SignUpView(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        print(form)
        if form.is_valid():
            print('validddd')
            user=form.save()
            #login(request,user)
            return redirect('core:login')
        messages.error(request, "Unsuccessful registration. Invalid information.")
        return render(request,'core/signup.html',
                      {'form':form})
    else:
        form=SignUpForm()
        return render(request,'core/signup.html',
                      {'form':form})
def LogInView(request):
    if request.method=='POST':
        form =LoginForm(request, data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password') 
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('core:index')
            messages.error(request,"Invalid username or password.")
        messages.error(request,"Invalid username or password.")
        return render(request,'core/login.html',{'form':form})
    else:
        form=AuthenticationForm()
        return render(request,'core/login.html',{'form':form}) 
            
        
            
    
    pass
    
def Contact(request):
    return render(request,'core/contact.html')
@login_required
def detailPage(request,pk):
    item=get_object_or_404(Item,pk=pk)
    itemCat=item.Category.name
    related_items=Item.objects.filter(Category__name=itemCat,is_sold=False).exclude(pk=pk)[:3]
    return render(request,'core/detail.html',{'item':item,'related_items':related_items})
    

dashbord/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from item.models import Item
# Create your views here.
app_name='dashbord'
@login_required
def Index(request):
    items=Item.objects.filter(created_by=request.user)
    return render(request,'dashboard/index.html',{'items':items})
    

item/views.py
from django.shortcuts import render,redirect
from .models import Item
from .forms import CreateItemForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render ,get_object_or_404
# Create your views here.
@login_required
def AddItemView(request):
   
   if request.method=='POST':
      form= CreateItemForm(request.POST, request.FILES)
      if form.is_valid():
         #add item to database
         item=form.save(commit=False)
         item.created_by=request.user
         item.save()
         return redirect('item:detail',pk=item.id)
         
      return render(request,'item/createItem.html',
                 {'form':form}) 
         
   else:
      form= CreateItemForm()
      #get 
      return render(request,'item/createItem.html',
                 {'form':form}) 

core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
<head>
  <title>  {%block title %}{% endblock title%} |Puddle</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
{% block BodyContent%}

{% endblock BodyContent%}
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact Page {%endblock title%}
{% block BodyContent %}
{% include 'core/navbar.html' %}
<h1> Contact </h1>
{% include 'core/footer.html' %}
{% endblock BodyContent %}

core/templates/core/detail.html
{% extends 'core/base.html' %}
{% block title %} {{item.name}} {% endblock title%}

{% block BodyContent%}
{% include 'core/navbar.html '%}

<div class="grid grid-cols-5 gap-6">
<div class="col-span-3">
     {% load static%}
<img src="{% get_media_prefix %}{{item.image}}" class="rounded-xl">
</div>

<div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{item.name}}</h1>
    <p class="text-gray-500"><strong> Price :</strong>{{item.price}}</p>
    <p class="text-gray-500">Seller :{{item.created_by}}</p>
<p class="text-gray-700">

    <strong> {{item.descreption}}</strong> 
</p><a href="#" class="inline-block mt-6 px-6 py-3 text-lg bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
</div>
<h2 class="mb-6 text-3xl">Related Items</h2>

{% for re_item in related_items%}
{{ re_item}}
{%endfor%}

</div>

{% endblock BodyContent %}

core/templates/core/footer.html
<footer class="py-6 px-6 flex justify-between bg-gray-800">

<div class="w-2/3 pr-10">
    <h3 class="mb-5 font-semibold text-gray-400">About</h3>
<p class="text-lg text-gray-500 ">Lorem blah ndj ,dzl</p>
</div>
<div class="w-1/3">
<h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
<ul class="space-y-z">
    <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
    <li> <a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contac</a></li>
    <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
    <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>

</ul>
</div>


</div>
</footer>

core/templates/core/header.html
<header>
</header>

core/templates/core/index.html
{% extends 'core/base.html'%}
{% block title %} Index Page {% endblock title %}
{% block BodyContent %}


{% include 'core/header.html' %}
{% include 'core/navbar.html' %}
<div class="mt-6  px-6 py-12 bg-gray-col-100 rounded-xl">
{% if items %}
<h2 class="mb-12 text-2xl text-center">Newest Items</h2>
<div class="grid  grid-cols-3 gap-3">   
{% for item in items %}
<div>
    <a href="{% url 'item:detail' item.id %}">
        <div>
            {% load static %}
            <img src="{% get_media_prefix %}{{item.image}}" width="300px" height="300px" class="rounded">
        </div>
        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{item.name}}</h2>
        <p class="text-gray-500">{{item.price}}</p>
        <div>
            {{item.Category.name}}
        </div>
        </div>

    </a>
</div>
{% endfor %}
</div>
{% endif %}
</div>
{% if categories %}
<h2 class="mb-12 text-2xl text-center">Categories</h2>

<div class="grid  grid-cols-3 gap-3">   
{% for category in categories%}

<div>
    <a href="#">

        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{category.name}}</h2>
            <p>{{ category.items.count}} Items</p>
        </div>

    </a>
</div>

{%endfor%}
</div>
{% endif%}

{% include 'core/footer.html' %}
{% endblock BodyContent %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Sign up Page{% endblock title%}
{% block BodyContent %}
{% include 'core/navbar.html' %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="inline-block mb-2">Username :</label>
    {{form.username}}
    </div>
    <div class="mb-3">
        <label class="inline-block mb-2">Password</label>
    {{form.password}}
    </div>
    {% if form.errors or form.non_field_errors%}

    {% for field in form %}
    {{ field.errors}}
    {%endfor%}
    {{ form.non_field_errors}}
    {% endif%}
<button typ="submit" >Log In</button>
</form>

{% endblock BodyContent%}

core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %} Log Out Page Page{% endblock title%}
{% block BodyContent %}
{% include 'core/navbar.html' %}

<h1> You Log Out</h1>
{% endblock BodyContent %}

core/templates/core/navbar.html
<nav class="py-6 px-6 flex justify-between items-center border-b borsder-gray-200">

    <a href='{% url 'core:index' %}' class="text-xl font-semibold">Puddle</a>
<div class="space-x-6">
<a href="{% url 'item:add-item' %}" class="text-lg font-semibold hover:text-gray-500">
    New Item
</a>

<a href="{% url 'core:index' %}" class="text-lg font-semibold hover:text-gray-500">
  {{request.user.username}}
</a>
{% if request.user.is_authenticated%}
<a href="{% url 'dashbord:index' %}" class="px-6 text-lg font-semibold bg-teal-500 py-3 text-white rounded-xl hover:bg-gray-500 text-white rounded-xl hoverbg-teal-700">
   Dashboard
    </a>

<a href="{% url 'core:logout' %}" class="px-6 text-lg font-semibold bg-teal-500 py-3 text-white rounded-xl hover:bg-gray-500 text-white rounded-xl hoverbg-teal-700">
Log Out
</a>

    {% else%}

    <a href="{% url 'core:signup' %}" class="px-6 text-lg font-semibold bg-teal-500 py-3 text-white rounded-xl hover:bg-gray-500 text-white rounded-xl hoverbg-teal-700">
        Sign up
        </a>    
        
        <a href="{% url 'core:login' %}" class="px-6 text-lg font-semibold bg-gray-500 py-3 text-white rounded-xl hover:bg-gray-500 text-white rounded-xl hoverbg-teal-700">
           Log In
            </a>
    {% endif%}
</div >

</nav>

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign up Page{% endblock title%}

{% block BodyContent %}
{% include 'core/navbar.html' %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
<h1 class="mb-6 text-3xl">Sign Up</h1>
    <form method="POST">

{% csrf_token %}

<div class="mb-3">
    <label class="inline-block mb-2">Username</label>
{{form.username}}
</div>

<div class="mb-3">
    <label class="inline-block mb-2">Email</label>
{{form.email}}
</div>
<div class="mb-3">
    <label class="inline-block mb-2">Password</label>
{{form.password1}}
</div>
<div class="mb-3">
    <label class="inline-block mb-2">Re enter Password</label>
    {{form.password2}}
</div>
{% if form.errors or form.non_field_errors%}

{% for field in form %}
{{ field.errors}}
{%endfor%}
{{ form.non_field_errors}}
{% endif%}
<button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700">Sign Up</button>
</form>
</div>
{% endblock BodyContent%}

dashbord/templates/dashboard/index.html
{% extends 'core/base.html'%}
{% block title %} Index Page {% endblock title %}
{% block BodyContent %}


{% include 'core/header.html' %}
{% include 'core/navbar.html' %}
<div class="mt-6  px-6 py-12 bg-gray-col-100 rounded-xl">
{% if items %}
<h2 class="mb-12 text-2xl text-center">My Items</h2>
<div class="grid  grid-cols-3 gap-3">   
{% for item in items %}
<div>
    <a href="{% url 'item:detail' item.id %}">
        <div>
            {% load static %}
            <img src="{% get_media_prefix %}{{item.image}}" width="300px" height="300px" class="rounded">
        </div>
        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{item.name}}</h2>
        <p class="text-gray-500">{{item.price}}</p>
        <div>
            {{item.Category.name}}
        </div>
        </div>

    </a>
</div>
{% endfor %}
</div>
{% endif %}
</div>


{% include 'core/footer.html' %}
{% endblock BodyContent %}

item/templates/item/createItem.html
{% extends 'core/base.html' %}

{% block title %} Add New Item{% endblock title%}

{% block BodyContent%}
{% include 'core/navbar.html' %}

<h1>Add New Item </h1>
<form  method='POST' enctype="multipart/form-data" >
{% csrf_token %}
{{ form.as_p}}
{% if form.errors or form.non_field_errors%}

{% for field in form %}
{{ field.errors}}
{%endfor%}
{{ form.non_field_errors}}
{% endif%}
<button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700" type="submit" >Add Item</button>
</form>
{% endblock BodyContent%}